# Artificial Neural Network

# 1. Data Preprocessing


### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.0.0'

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding Categorical Data

Label Encode 'Gender' field

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


### One Hot Encoding the Geography Column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

### Split the data into train and test cells

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature scaling
Feature scaling is very much essential for Deep Learning.
Need to train all the features in the dataset.

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


# 2. Building ANN

### Initializing the ANN

In [12]:
ann = tf.keras.Sequential()

### Adding input layer

In [14]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding second hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding output layer

In [16]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

# 3.Training the ANN

### Compile the ANN 

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrices = ['accuracy'])

### Training the ANN ojn training set

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 3s 323us/sample - loss: 0.5768
Epoch 2/100
8000/8000 [==============================] - 1s 138us/sample - loss: 0.4852
Epoch 3/100
8000/8000 [==============================] - 1s 137us/sample - loss: 0.4553
Epoch 4/100
8000/8000 [==============================] - 1s 136us/sample - loss: 0.4403
Epoch 5/100
8000/8000 [==============================] - 1s 118us/sample - loss: 0.4309
Epoch 6/100
8000/8000 [==============================] - 1s 106us/sample - loss: 0.4246
Epoch 7/100
8000/8000 [==============================] - 1s 138us/sample - loss: 0.4197
Epoch 8/100
8000/8000 [==============================] - 1s 136us/sample - loss: 0.4167
Epoch 9/100
8000/8000 [==============================] - 1s 118us/sample - loss: 0.4140
Epoch 10/100
8000/8000 [==============================] - 1s 93us/sample - loss: 0.4126
Epoch 11/100
8000/8000 [==============================] - 1s 102us/sample - loss: 0.4108
Epoch 12/

8000/8000 [==============================] - 1s 94us/sample - loss: 0.3330
Epoch 94/100
8000/8000 [==============================] - 1s 113us/sample - loss: 0.3326
Epoch 95/100
8000/8000 [==============================] - 1s 81us/sample - loss: 0.3331
Epoch 96/100
8000/8000 [==============================] - ETA: 0s - loss: 0.331 - 1s 87us/sample - loss: 0.3331
Epoch 97/100
8000/8000 [==============================] - 1s 88us/sample - loss: 0.3326
Epoch 98/100
8000/8000 [==============================] - 1s 80us/sample - loss: 0.3328
Epoch 99/100
8000/8000 [==============================] - 1s 87us/sample - loss: 0.3326
Epoch 100/100
8000/8000 [==============================] - 1s 92us/sample - loss: 0.3327


# 4. Making predictions and evaluating the model

In [22]:
print(ann.predict(sc.transform([[1,0,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


### Predicting the test set result

In [24]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)), 1))


[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the confusion matrix

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1516   79]
 [ 194  211]]


0.8635